### ISSUE TITLE
Error on OS X 10.10.1

### ISSUE THREAD

**Issue by yvangodard** [univ-of-utah-marriott-library-apple/firmware_version_checker#2]
On OS X 10.10.1 / Python 2.7.6
An error appends ....

The operation couldn’t be completed. (NSURLErrorDomain error -1012.)
Traceback (most recent call last):
  File "./check_firmware.py", line 390, in <module>
    main(logger, args.verbose)
  File "./check_firmware.py", line 61, in main
    sw_update_firmware_available = len(sw_update_firmware) != 0
TypeError: object of type 'bool' has no len()

**Comment by uurazzle** [comment]
Hello Yvan:

Sorry about the issue, we would troubleshoot and it and post a fix.

On Feb 13, 2015, at 1:27 AM, Yvan GODARD <notifications@github.com<mailto:notifications@github.com>> wrote:

On OS X 10.10.1 / Python 2.7.6
An error appends ....

The operation couldn’t be completed. (NSURLErrorDomain error -1012.)
Traceback (most recent call last):
File "./check_firmware.py", line 390, in
main(logger, args.verbose)
File "./check_firmware.py", line 61, in main
sw_update_firmware_available = len(sw_update_firmware) != 0
TypeError: object of type 'bool' has no len()

—
Reply to this email directly or view it on GitHubhttps://github.com/univ-of-utah-marriott-library-apple/firmware_version_checker/issues/2.

Thanks:

Richard Glaser
University of Utah, Marriott Library ITS
richard.glaser@utah.edumailto:richard.glaser@utah.edu

**Comment by pdarragh** [comment]
Yvan,

I've duplicated the error on my own machine running 10.10.2. It's very interesting because I don't have the same issue in Mavericks... I'm looking into it and will report back with my findings. Worst case scenario is I'll have to rewrite part of the code to handle this differently.

Thanks,
Pierce

**Comment by pdarragh** [comment]
Apparently I didn't check some of my return values carefully enough, which is what caused the issue. I've incorporated the changes into v. 1.0.1.
